### ISSUE TITLE
我在启动项目的时候访问/docs swagger文档的时候，无限重定向

### ISSUE THREAD

**Issue by ranyong1997** [vvandk/kinit#1]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/67427627/230751042-d1a7b36a-283c-43d3-b865-1d400b1bb025.png">

**Comment by ranyong1997** [comment]
使用的是mac系统
<img width="622" alt="image" src="https://user-images.githubusercontent.com/67427627/230750274-a2814d06-a384-42f0-8440-e39c03e6ae33.png">

**Comment by vvandk** [comment]
已修复，请获取最新代码
