### ISSUE TITLE
你好，基本的crud能自动生成吗

### ISSUE THREAD

**Issue by dgo2dance** [vvandk/kinit#14]
你好，基本的crud能自动生成吗

**Comment by vvandk** [comment]
目前没有实现

**Comment by ontisme** [comment]
若未來有開發的意向，我覺得 [GinVueAdmin](https://github.com/flipped-aurora/gin-vue-admin) 的思路可以參考看看

**Comment by vvandk** [comment]
可以在最新代码实习基于 ORM 模型生成基本的 crud
