### ISSUE TITLE
kinit-api only supports Win system?

### ISSUE THREAD

**Issue by femj007** [vvandk/kinit#17]
`from win32com.client import gencache
import comtypes.client`

I find two useless functions in kinit-api/utils/tools.py: ppt_to_pdf_1 and ppt_to_pdf_2, which import two packages only supported on the Windows system. Does kinit-api only support on win? I am not sure why to create these two functions. Seems they are not used in codes.

**Comment by vvandk** [comment]
这两个函数只是提供出来，但是并未使用，不需要可以直接删除
