### ISSUE TITLE
 Could not find a version that satisfies the requirement pywin32==306 (from versions: none)

### ISSUE THREAD

**Issue by hezuogongying** [vvandk/kinit#19]
在centos7.9部署docler时

 ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: none)
#0 18.73 ERROR: No matching distribution found for pywin32==306

failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/" did not complete successfully: exit code: 1
报错了
确定要用到windows的pywin32吗？不安装这个行吗

**Comment by vvandk** [comment]
不安装不影响程序运行
