### ISSUE TITLE
执行  python3 main.py init --env dev   报错  python 3.10.11

### ISSUE THREAD

**Issue by swortect** [vvandk/kinit#27]
开始初始化数据
online
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "H:\python\venv\Scripts\alembic.exe\__main__.py", line 7, in <module>
  File "H:\python\venv\Lib\site-packages\alembic\config.py", line 641, in main
    CommandLine(prog=prog).main(argv=argv)
  File "H:\python\venv\Lib\site-packages\alembic\config.py", line 631, in main
    self.run_cmd(cfg, options)
  File "H:\python\venv\Lib\site-packages\alembic\config.py", line 608, in run_cmd
    fn(
  File "H:\python\venv\Lib\site-packages\alembic\command.py", line 236, in revision
    script_directory.run_env()
  File "H:\python\venv\Lib\site-packages\alembic\script\base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "H:\python\venv\Lib\site-packages\alembic\util\pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\venv\Lib\site-packages\alembic\util\pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\python\kinit\kinit-api\alembic\env.py", line 92, in <module>
    run_migrations_online()
  File "H:\python\kinit\kinit-api\alembic\env.py", line 75, in run_migrations_online
    with connectable.connect() as connection:
         ^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3269, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3293, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "H:\python\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "H:\python\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 284, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 678, in __init__
    self.__connect()
  File "H:\python\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 902, in __connect
    with util.safe_reraise():
  File "H:\python\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "H:\python\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\venv\Lib\site-packages\sqlalchemy\dialects\mysql\asyncmy.py", line 281, in connect
    await_only(creator_fn(*arg, **kw)),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\python\venv\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 121, in await_only
    raise exc.MissingGreenlet(
sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: 
https://sqlalche.me/e/20/xd2s)
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ H:\python\kinit\kinit-api\main.py:100 in init                                                    │
│                                                                                                  │
│    97 │   """                                                                                    │
│    98 │   print("开始初始化数据")                                                                │
│    99 │   data = InitializeData()                                                                │
│ ❱ 100 │   asyncio.run(data.run(env))                                                             │
│   101                                                                                            │
│   102                                                                                            │
│   103 @shell_app.command()                                                                       │
│                                                                                                  │
│ ╭────────────────────────────────────── locals ──────────────────────────────────────╮           │
│ │ data = <scripts.initialize.initialize.InitializeData object at 0x0000024418567150> │           │
│ │  env = <Environment.dev: 'dev'>                                                    │           │
│ ╰────────────────────────────────────────────────────────────────────────────────────╯           │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py:190 in run │
│                                                                                                  │
│   187 │   │   │   "asyncio.run() cannot be called from a running event loop")                    │
│   188 │                                                                                          │
│   189 │   with Runner(debug=debug) as runner:                                                    │
│ ❱ 190 │   │   return runner.run(main)                                                            │
│   191                                                                                            │
│   192                                                                                            │
│   193 def _cancel_all_tasks(loop):                                                               │
│                                                                                                  │
│ ╭─────────────────────────────── locals ───────────────────────────────╮                         │
│ │  debug = None                                                        │                         │
│ │   main = <coroutine object InitializeData.run at 0x0000024419884E50> │                         │
│ │ runner = <asyncio.runners.Runner object at 0x00000244198A8B90>       │                         │
│ ╰──────────────────────────────────────────────────────────────────────╯                         │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py:118 in run │
│                                                                                                  │
│   115 │   │                                                                                      │
│   116 │   │   self._interrupt_count = 0                                                          │
│   117 │   │   try:                                                                               │
│ ❱ 118 │   │   │   return self._loop.run_until_complete(task)                                     │
│   119 │   │   except exceptions.CancelledError:                                                  │
│   120 │   │   │   if self._interrupt_count > 0:                                                  │
│   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                 │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │        context = <_contextvars.Context object at 0x000002441857D880>                         │ │
│ │           coro = <coroutine object InitializeData.run at 0x0000024419884E50>                 │ │
│ │           self = <asyncio.runners.Runner object at 0x00000244198A8B90>                       │ │
│ │ sigint_handler = functools.partial(<bound method Runner._on_sigint of                        │ │
│ │                  <asyncio.runners.Runner object at 0x00000244198A8B90>>, main_task=<Task     │ │
│ │                  finished name='Task-1' coro=<InitializeData.run() done, defined at          │ │
│ │                  H:\python\kinit\kinit-api\scripts\initialize\initialize.py:163>             │ │
│ │                  exception=CalledProcessError(1, ['alembic', '--name', 'dev', 'revision',    │ │
│ │                  '--autogenerate', '-m', '3.10.0'])>)                                        │ │
│ │           task = <Task finished name='Task-1' coro=<InitializeData.run() done, defined at    │ │
│ │                  H:\python\kinit\kinit-api\scripts\initialize\initialize.py:163>             │ │
│ │                  exception=CalledProcessError(1, ['alembic', '--name', 'dev', 'revision',    │ │
│ │                  '--autogenerate', '-m', '3.10.0'])>                                         │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py:654 in │
│ run_until_complete                                                                               │
│                                                                                                  │
│    651 │   │   if not future.done():                                                             │
│    652 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    653 │   │                                                                                     │
│ ❱  654 │   │   return future.result()                                                            │
│    655 │                                                                                         │
│    656 │   def stop(self):                                                                       │
│    657 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   future = <Task finished name='Task-1' coro=<InitializeData.run() done, defined at          │ │
│ │            H:\python\kinit\kinit-api\scripts\initialize\initialize.py:163>                   │ │
│ │            exception=CalledProcessError(1, ['alembic', '--name', 'dev', 'revision',          │ │
│ │            '--autogenerate', '-m', '3.10.0'])>                                               │ │
│ │ new_task = False                                                                             │ │
│ │     self = <ProactorEventLoop running=False closed=True debug=False>                         │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ H:\python\kinit\kinit-api\scripts\initialize\initialize.py:167 in run                            │
│                                                                                                  │
│   164 │   │   """                                                                                │
│   165 │   │   执行初始化工作                                                                     │
│   166 │   │   """                                                                                │
│ ❱ 167 │   │   self.migrate_model(env)                                                            │
│   168 │   │   await self.generate_menu()                                                         │
│   169 │   │   await self.generate_role()                                                         │
│   170 │   │   await self.generate_dept()                                                         │
│                                                                                                  │
│ ╭────────────────────────────────────── locals ──────────────────────────────────────╮           │
│ │  env = <Environment.dev: 'dev'>                                                    │           │
│ │ self = <scripts.initialize.initialize.InitializeData object at 0x0000024418567150> │           │
│ ╰────────────────────────────────────────────────────────────────────────────────────╯           │
│                                                                                                  │
│ H:\python\kinit\kinit-api\scripts\initialize\initialize.py:51 in migrate_model                   │
│                                                                                                  │
│    48 │   │   """                                                                                │
│    49 │   │   模型迁移映射到数据库                                                               │
│    50 │   │   """                                                                                │
│ ❱  51 │   │   subprocess.check_call(['alembic', '--name', f'{env.value}', 'revision', '--autog   │
│    52 │   │   subprocess.check_call(['alembic', '--name', f'{env.value}', 'upgrade', 'head'],    │
│    53 │   │   print(f"环境：{env}  {VERSION} 数据库表迁移完成")                                  │
│    54                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────── locals ───────────────────────────╮                                 │
│ │ cls = <class 'scripts.initialize.initialize.InitializeData'> │                                 │
│ │ env = <Environment.dev: 'dev'>                               │                                 │
│ ╰──────────────────────────────────────────────────────────────╯                                 │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py:413 in          │
│ check_call                                                                                       │
│                                                                                                  │
│    410 │   │   cmd = kwargs.get("args")                                                          │
│    411 │   │   if cmd is None:                                                                   │
│    412 │   │   │   cmd = popenargs[0]                                                            │
│ ❱  413 │   │   raise CalledProcessError(retcode, cmd)                                            │
│    414 │   return 0                                                                              │
│    415                                                                                           │
│    416                                                                                           │
│                                                                                                  │
│ ╭───────────────────────────────────────── locals ──────────────────────────────────────────╮    │
│ │       cmd = ['alembic', '--name', 'dev', 'revision', '--autogenerate', '-m', '3.10.0']    │    │
│ │    kwargs = {'cwd': 'H:\\python\\kinit\\kinit-api'}                                       │    │
│ │ popenargs = (['alembic', '--name', 'dev', 'revision', '--autogenerate', '-m', '3.10.0'],) │    │
│ │   retcode = 1                                                                             │    │
│ ╰───────────────────────────────────────────────────────────────────────────────────────────╯    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['alembic', '--name', 'dev', 'revision', '--autogenerate', '-m', '3.10.0']' returned non-zero exit status 1.

**Comment by vvandk** [comment]
参考：https://gitee.com/ktianc/kinit/issues/I94B9F
