### ISSUE TITLE
你好，这是我发现用fastapi写的最好的开源项目，有交流群吗

### ISSUE THREAD

**Issue by uspear** [vvandk/kinit#7]
1、项目一定要用MongoDB才能启动吗？这样是不是里面的mysql没有用到

**Comment by vvandk** [comment]
redis与mongodb都不是必须的
mysql 是必须的
在配置文件中关闭即可
1. academy-api/application/config/development.py
2. academy-api/application/config/production.py
不用mongodb的话就不能使用定时任务和操作日志的功能，因为这两个功能使用的是Mongodb数据库

**Comment by orency** [comment]
配置不起作用,禁用了照样有redis超时连接的错误导致项目根本无法启动

**Comment by orency** [comment]
找到原因了原来是aioredis包与python3.11不兼容
解决方法是搜索项目文件把所有的
```
from aioredis import Redis
```
改为
```
from redis.asyncio.client import Redis
```
