### ISSUE TITLE
可以增加  Pc 的微信登录吗

### ISSUE THREAD

**Issue by A2Data** [vvandk/kinit#8]
微信登录 pc 的好像是失效的 以及支付宝

**Comment by vvandk** [comment]
对的，PC端只支持手机号密码/短信验证码登录，目前还没接入微信登陆与支付宝接入的计划，因为官方接入需要企业认证

**Comment by A2Data** [comment]
公众号认证的就可以接入是吧

**Comment by A2Data** [comment]
我这边可以提供这个 测试，可以加一下吗？

附录：
大佬可否使用 pyenv 管理python 环境 和 pdm 来管理依赖包
